### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by JJJIANGJIANG** [zsnjuts/PaintWorks#4]
这个绘图程序的opengl需要重新配置吗#include <GL/glu.h>？我这里编译运行显示
H:\PaintWorks-master\glwidget.cpp:74: error: undefined reference to `_imp__glGetIntegerv@8'
H:\PaintWorks-master\glwidget.cpp:78: error: undefined reference to `_imp__glPixelStorei@8'
等错误，麻烦您了谢谢。

**Comment by zsnjuts** [comment]
应该是需要配置opengl的

**Comment by JJJIANGJIANG** [comment]
您好，如果我想在您的绘图基础上实现逐个点打印而不是直接画出，请问您有什么建议么，十分感谢
